config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :update, :destroy, :show] do
    resources :notes, only: [:create, :destroy]
  end

  root to: redirect("/bands")
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  note_text  :text             not null
#  user_id    :integer          not null
#  track_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ActiveRecord::Base
  validates :user_id, :track_id, :note_text, presence: true

  belongs_to :user
  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    if @note.save
      redirect_to track_url(@note.track_id)
    else
      redirect_to track_url(@note.track_id)
    end
  end

  def destroy
    @note = Note.find(params[:id]).destroy
    redirect_to track_url(@note.track_id)
  end

  private
  def note_params
    params.require(:note).permit(:note_text, :track_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<h4>New Note</h4>

<form action="<%= track_notes_url(track.id) %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="note_text">Note</label>
  <br>
  <textarea name="note[note_text]"
            rows="8"
            cols="40"
            id="note_text"></textarea>

  <input type="hidden"
          name="note[track_id]"
          value="<%= track.id %>">
  <br>
  <input type="submit" value="Submit">
</form>