config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :update, :destroy, :show] do
    resources :notes, only: [:create, :destroy]
  end

  root to: redirect("/bands")
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  name       :text             not null
#  track_num  :integer          not null
#  lyrics     :text
#  track_type :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  validates :album_id, :name, :track_num, :track_type, presence: true

  belongs_to :album
  has_many :notes, dependent: :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  def destroy
    @track = Track.find(params[:id]).destroy
    redirect_to album_url(@track.album_id)
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :track_num, :track_type, :lyrics)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% method = (track.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

     <% if flash.now[:errors] %>
       <% flash.now[:errors].each do |error| %>
        <%= error %><br />
       <% end %>
     <% end %>
   <br>

  <label for="track_album">Album:</label>
  <select name="track[album_id]"
          id="track_album">
    <option></option>
    <% Band.all.each do |band| %>
      <% band.albums.each do |album| %>
        <% selected = @track.album_id == album.id %>
        <option
          <%= selected ? "selected" : "" %>
          value="<%= album.id %>">
           <%= album.name %> by <%= band.name %>
        </option>
        <% end %>
    <% end %>
  </select>
  <br><br>

  <label for="track_name">Name:</label>
  <input type="text"
         name="track[name]"
         id="track_name"
         value="<%= @track.name %>">

<br><br>

  <label for="track_num">Track number</label>
  <input type="text"
         name="track[track_num]"
         id="track_num"
         value="<%= @track.track_num %>">
  <br>
<p>Track Type</p>
  <input type="radio"
         name="track[track_type]"
         id="track_type"
         value="regular"
         <%= "checked" if @track.track_type == "regular" %>>
  <label for="track_type">Regular</label>

  <input type="radio"
         name="track[track_type]"
         id="track_type"
         value="bonus"
         <%= "checked" if @track.track_type == "bonus" %>>
  <label for="track_type">Bonus</label>
<br>
  <textarea name="track[lyrics]"
            rows="8"
            cols="40">Lyrics</textarea>

<br><br>
<input type="submit" value="Create Track">
</form>

<br>

<%= link_to "All Bands", bands_url %>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h1>Add a Track to Album</h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>


<p>
  <%= ugly_lyrics(@track.lyrics).html_safe %>
</p>

<br><br><br>

<h4>Notes</h4>

<% @track.notes.each do |note| %>
  <p>
    <%= note.note_text %>
    <% if note.user_id == current_user.id %>
      <%= link_to "delete", track_note_url(@track.id ,note.id), :method => :delete %>
    <% end %>
  </p>

<% end %>

<%= render "notes/form", track: @track %>

<br>
<%= link_to "Back to Album", album_url(@track.album_id) %>
<br>
<%= link_to "All Bands", bands_url %>