config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :update, :destroy, :show] do
    resources :notes, only: [:create, :destroy]
  end

  root to: redirect("/bands")
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  name           :text             not null
#  band_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  recording_type :text
#

class Album < ActiveRecord::Base
  validates :name, :band_id, :recording_type, presence: true

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:name, :recording_type, :band_id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>
<% button = (album.persisted? ? "Edit Album" : "Create Album") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

   <% if flash.now[:errors] %>
     <% flash.now[:errors].each do |error| %>
      <%= error %><br />
     <% end %>
   <% end %>
 <br>
       
  <label for="album_band">Band:</label>
  <select name="album[band_id]"
          id="album_band">
    <option></option>
    <% Band.all.each do |band| %>
      <% selected = @album.band_id == band.id %>
      <option
        <%= selected ? "selected" : "" %>
        value="<%= band.id %>">
         <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="album_name">Album Title</label>
  <input type="text"
         name="album[name]"
         id="album_name"
         value="<%= @album.name %>">
  <br>

  <input type="radio"
         name="album[recording_type]"
         value="studio"
         id="album_recording_type_studio"
         <%= "checked" if @album.recording_type == "studio"  %>>
  <label for="album_recording_type_studio">Studio</label>

  <input type="radio"
         name="album[recording_type]"
         value="live"
         id="album_recording_type_studio"
         <%= "checked" if @album.recording_type == "live" %>>
  <label for="album_recording_type_studio">Live</label>
  <br>

<input type="submit" value="<%= button %>">
</form>

<br>
<%= link_to "All Bands", bands_url %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/new.html.erb
<h1>Create an Album</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<table>
  <tr>
    <th>number</th>
    <th>Title</th>
    <th>Type</th>
  </tr>

  <% @album.tracks.each do |track| %>
  <tr>
    <th>
    <%= track.track_num %>
    </th>
    <th>
      <%= link_to track.name, track_url(track) %>
    </th>
    <th>
      <%= track.track_type %>
    </th>
    <th>
      <%= link_to "Edit", edit_track_url(track) %>
    </th>
    <th>
      <%= link_to "Remove", track_url(track), :method => :delete %>
    </th>
  </tr>
  <% end %>
</table>

<br>
<%= link_to "Back to Band", band_url(@album.band_id) %>
<br>
<%= link_to "Add Tracks", new_album_track_url(@album) %>
<br>
<%= link_to "All Bands", bands_url %>