config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :update, :destroy, :show] do
    resources :notes, only: [:create, :destroy]
  end

  root to: redirect("/bands")
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find_by_id(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id]).destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>
<% button = (band.persisted? ? "Edit Band" : "Create Band") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
     <%= error %><br />
    <% end %>
  <% end %>
<br>
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name">Name of Band:</label>
  <input type="text"
         name="band[name]"
         id="band_name"
         value="<%= @band.name %>">
  <br>

  <input type="submit" value="<%= button %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands!!!!!</h1>

<ul>
<% @bands.each do |band| %>
<li>
  <%= link_to band.name, band_url(band) %>
</li>
<% end %>
<ul>

<br>
<%= link_to "Create a Band", "bands/new" %>

app/views/bands/new.html.erb
<h1>Create A Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<table>
  <tr>
    <th>albums</th>
  </tr>
  <% @band.albums.each do |album| %>
  <tr>
    <th>
      <%= link_to album.name, album_url(album.id) %>
    </th>
    <th>
      <%= link_to "Edit", edit_album_url(album) %>
    </th>
    <th>
      <%= link_to "Remove", album_url(album), :method => :delete %>
    </th>
  </tr>
  <% end %>
</table>

<br>
<%= link_to "Edit Band", edit_band_url(@band) %>
<%= link_to "Delete Band", band_url(@band), :method => :delete %>
<br>

<%= link_to "New Album", new_band_album_url(@band) %>
<br>
<%= link_to "All Bands", bands_url %>